<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="AdminITs-MacBook-Pro-2.local" name="testng.SignIn" tests="10" failures="0" timestamp="5 Nov 2015 13:44:56 GMT" time="480.590" errors="1">
  <testcase name="signIn" time="21.224" classname="testng.SignIn"/>
  <testcase name="signIn" time="37.573" classname="testng.SignIn"/>
  <testcase name="signIn" time="55.063" classname="testng.SignIn"/>
  <testcase name="signIn" time="63.408" classname="testng.SignIn"/>
  <testcase name="signIn" time="69.869" classname="testng.SignIn"/>
  <testcase name="signIn" time="46.660" classname="testng.SignIn"/>
  <testcase name="signIn" time="86.535" classname="testng.SignIn"/>
  <testcase name="signIn" time="14.546" classname="testng.SignIn">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.perfectomobile.test.BasicTest.reportFail(BasicTest.java:297)
	at testng.SignIn.signIn(SignIn.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- signIn -->
  <testcase name="signIn" time="27.931" classname="testng.SignIn"/>
  <testcase name="signIn" time="57.781" classname="testng.SignIn"/>
</testsuite> <!-- testng.SignIn -->
