<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WIN-JSR14J9SQIC" name="Test" tests="15" failures="5" timestamp="18 Sep 2015 13:38:02 GMT" time="289.391" errors="0">
  <testcase name="signIn" time="17.339" classname="testng.SignIn"/>
  <testcase name="signIn" time="28.006" classname="testng.SignIn"/>
  <testcase name="signIn" time="50.344" classname="testng.SignIn"/>
  <testcase name="signIn" time="55.426" classname="testng.SignIn"/>
  <testcase name="signIn" time="52.593" classname="testng.SignIn"/>
  <testcase name="signIn" time="57.379" classname="testng.SignIn"/>
  <testcase name="signIn" time="62.445" classname="testng.SignIn"/>
  <testcase name="signIn" time="47.141" classname="testng.SignIn">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.perfectomobile.test.BasicTest.reportFail(BasicTest.java:295)
	at testng.SignIn.signIn(SignIn.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- signIn -->
  <testcase name="signIn" time="58.613" classname="testng.SignIn">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.perfectomobile.test.BasicTest.reportFail(BasicTest.java:295)
	at testng.SignIn.signIn(SignIn.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- signIn -->
  <testcase name="signIn" time="88.1" classname="testng.SignIn"/>
  <testcase name="signIn" time="101.153" classname="testng.SignIn"/>
  <testcase name="signIn" time="94.299" classname="testng.SignIn"/>
  <testcase name="signIn" time="85.353" classname="testng.SignIn">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.perfectomobile.test.BasicTest.reportFail(BasicTest.java:295)
	at testng.SignIn.signIn(SignIn.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- signIn -->
  <testcase name="signIn" time="92.699" classname="testng.SignIn">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.perfectomobile.test.BasicTest.reportFail(BasicTest.java:295)
	at testng.SignIn.signIn(SignIn.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- signIn -->
  <testcase name="signIn" time="89.902" classname="testng.SignIn">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.perfectomobile.test.BasicTest.reportFail(BasicTest.java:295)
	at testng.SignIn.signIn(SignIn.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- signIn -->
</testsuite> <!-- Test -->
